name: Simple CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake clang-format
    
    - name: Check code formatting
      run: |
        find src include tests -name "*.cpp" -o -name "*.h" | \
        xargs clang-format --dry-run --Werror
    
    - name: Build and test
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        ctest --test-dir build --output-on-failure
