name: PR Assignee/Reviewer Check

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, review_requested, review_request_removed, assigned, unassigned]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR assignment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;

            // Fetch latest PR info
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const assignees = pr.assignees || [];
            const reviewers = pr.requested_reviewers || [];

            const errors = [];

            // Rule 1: Exactly one assignee
            if (assignees.length !== 1) {
              errors.push(`PR must have exactly ONE assignee (found ${assignees.length}).`);
            }

            // Rule 2: Exactly one reviewer
            if (reviewers.length !== 1) {
              errors.push(`PR must have exactly ONE reviewer (found ${reviewers.length}).`);
            }

            // Rule 3: Assignee ≠ Reviewer
            if (assignees.length === 1 && reviewers.length === 1) {
              if (assignees[0].login === reviewers[0].login) {
                errors.push(`Assignee and reviewer cannot be the same person.`);
              }
            }

            if (errors.length > 0) {
              core.setFailed(errors.join('\n'));
            } else {
              console.log("✅ Assignee and reviewer setup looks good!");
            }
