name: PR Assignee/Reviewer Check

on:
  pull_request:
    # Only run on key events to reduce notification spam
    types: [opened, ready_for_review, assigned, review_requested]
  schedule:
    # Run once per minute to check existing PRs
    - cron: '*/1 * * * *'

jobs:
  validate-pr:
    # ✅ Prevent job from ever running on main
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check PR assignment
        uses: actions/github-script@v7
        with:
          script: |
            let prsToCheck = [];

            if (context.eventName === 'pull_request') {
              // For PR events, check only the current PR
              prsToCheck = [context.payload.pull_request.number];
            }

            let hasErrors = false;

            for (const prNumber of prsToCheck) {
              try {
                const { data: pr } = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                });

                const assignees = pr.assignees || [];
                const reviewers = pr.requested_reviewers || [];
                const errors = [];

                if (assignees.length !== 1) {
                  errors.push(`PR #${prNumber} must have exactly ONE assignee (found ${assignees.length}).`);
                }

                if (reviewers.length !== 1) {
                  errors.push(`PR #${prNumber} must have exactly ONE reviewer (found ${reviewers.length}).`);
                }

                if (assignees.length === 1 && reviewers.length === 1) {
                  if (assignees[0].login === reviewers[0].login) {
                    errors.push(`PR #${prNumber}: Assignee and reviewer cannot be the same person.`);
                  }
                }

                if (errors.length > 0) {
                  console.error(errors.join('\n'));
                  hasErrors = true;
                } else {
                  console.log(`✅ PR #${prNumber}: Assignee and reviewer setup looks good!`);
                }
              } catch (error) {
                console.error(`Error checking PR #${prNumber}: ${error.message}`);
              }
            }

            if (hasErrors) {
              core.setFailed("One or more PRs have assignee/reviewer issues. Check the logs above.");
            }
